# Generated by Django 4.1.2 on 2022-11-13 00:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpaymentinformation',
            name='credit_card_number',
        ),
        migrations.AddField(
            model_name='userpaymentinformation',
            name='cardnumber',
            field=models.CharField(default=1234567812345678, max_length=16, validators=[django.core.validators.MinLengthValidator(16)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='foodordertable',
            name='order_id',
            field=models.CharField(default='10q8YMsS', max_length=8),
        ),
        migrations.AlterField(
            model_name='tablebooking',
            name='booking_id',
            field=models.CharField(default='8jpww', max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='userpaymentinformation',
            name='cvv',
            field=models.CharField(max_length=3, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
